name: Amplify Headless CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "19"

      - name: Install dependencies
        run: npm install

      - name: Install Amplify CLI
        run: npm install -g @aws-amplify/cli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2 # Ensure this matches your project's region

      - name: Install or Update AWS CLI
        run: |
          if [ -d "/usr/local/aws-cli/v2/current" ]; then
            echo "AWS CLI v2 is already installed. Updating..."
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip -o awscliv2.zip
            sudo ./aws/install --update
          else
            echo "Installing AWS CLI v2..."
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip -o awscliv2.zip
            sudo ./aws/install
          fi

      - name: Amplify Pull (Headless)
        run: |
          amplify pull \
          --appId d3ss9pq6bcenn \
          --envName dev \
          --yes

      - name: Amplify Push
        run: amplify push --yes

      - name: Amplify Publish
        run: amplify publish --yes

      # Remove the amplify init and load config steps if they are not necessary
      # Add additional steps as needed
